name:                interpreter-in-haskell
version:             0.1.0.0
github:              "githubuser/interpreter-in-haskell"
license:             BSD3
author:              "mm1995tk"
copyright:           "2022 mm1995tk"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/interpreter-in-haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - megaparsec
  - transformers

# default-language: GHC2021

default-extensions:
  - OverloadedStrings
  - RecordWildCards
  - MultiWayIf
  - TupleSections
  - LambdaCase
  - BangPatterns
  - DeriveGeneric
  - DerivingVia
  - DeriveFunctor
  - GADTs
  - GADTSyntax
  - NamedFieldPuns

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  interpreter-in-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies: interpreter-in-haskell

tests:
  interpreter-in-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    build-tools:
      - tasty-discover

    dependencies: 
      - tasty
      - tasty-hspec
      - hspec
      - hspec-megaparsec
      - interpreter-in-haskell
