resolver: lts-19.33
packages:
- .


# extra-deps:
#   - haddock-api-2.25.1@sha256:37839471c3a5937d6a12e6a17cedd2e58ba98d235ee7f6f66293408b9bb9717f,6061
# build:
#   haddock: true
#   haddock-arguments:
#     haddock-args:
#     - --odir=.haddock
#   open-haddocks: false
#   haddock-internal: false
#   haddock-hyperlink-source: true